dataset_name: 'soyageing'
dataset_root_path: '../../data/soyageing'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: '.'
folder_val: '.'
folder_test: '.'
df_classid_classname: False
