dataset_name: 'soygene'
dataset_root_path: '../../data/soygene'
df_train: 'train.csv'
df_trainval: train_val.csv
df_val: 'val.csv'
df_test: 'test.csv'
folder_train: 'images'
folder_val: 'images'
folder_test: 'images'
df_classid_classname: False
